/uwb_node:
  ros__parameters:
    anchors_calib_files:
    - /home/tom/Documents/PhD/limo_ws/src/uwb-ros2/uwb-serial-ros2/config/calib1.csv
    boudrate: 115200
    compensation: 2
    max_range_m: 20.0
    min_range_m: 0.1
    namespace: ''
    timer_rate_s: 0.02
    topic_name: uwb/range
    usb_port: /dev/ttyACM0
    use_sim_time: false

